import pathlib
import re
from dataclasses import dataclass
from pathlib import PurePath

import git

from .processor import Processor


@dataclass
class File:
    name: str
    src_path: PurePath
    content: str | None


@dataclass
class Dir:
    path: pathlib.Path
    files: list[File]
    dirs: list["Dir"]


def _scan(
    path: pathlib.Path,
    processors: list[Processor],
    ignore_patterns: list[re.Pattern],
    repo: git.Repo,
    depth: int,
    max_depth: int | None,
) -> Dir:
    dir = Dir(path=path, files=[], dirs=[])
    entries = list(path.iterdir())
    if not entries:
        return dir
    resolved_entries = {str(entry.resolve()) for entry in entries}

    # remove any entries which match our ignore patterns (e.g. autogenerated files)
    ignored = {
        resolved_entry
        for resolved_entry in resolved_entries
        if any(
            re.search(pattern, resolved_entry) is not None
            for pattern in ignore_patterns
        )
    }
    # also ignore anything .gitignored (doing this second because it's a likely a little
    # more time consuming)
    remaining_entries = resolved_entries - ignored
    if remaining_entries:
        ignored |= set(repo.ignored(*remaining_entries))

    for entry in entries:
        # FIXME: At some point we should only ignore .git in the root directory
        if entry.name == ".git" or str(entry.resolve()) in ignored:
            continue
        if entry.is_file():
            for processor in processors:
                if processor.pattern.search(str(entry)):
                    content = entry.read_text() if processor.read_content else None
                    dir.files.append(
                        File(
                            name=entry.name,
                            src_path=(path / entry.name),
                            content=content,
                        )
                    )
        elif entry.is_dir() and (max_depth is None or depth < max_depth):
            dir.dirs.append(
                _scan(
                    path / entry.name,
                    processors,
                    ignore_patterns,
                    repo,
                    depth + 1,
                    max_depth,
                )
            )

    return dir


def scan(
    path: pathlib.Path,
    processors: list[Processor],
    ignore_patterns: list[re.Pattern] | None = None,
    subdirs: list[pathlib.Path] | None = None,
    max_depth: int | None = None,
) -> tuple[Dir, git.Repo]:
    """
    Scans a GitHub repository for files and subdirectories, returning a data
    structure representing the directory tree.

    Takes in a list of processors to figure out which files should be included
    in the returned tree.

    Under the hood, this uses the `git` library to scan the repository, skipping
    files in .gitignore.

    This step does not do any post-processing of the files, though their
    content is read in if one of their processors requires it.

    Returns a tuple of (Dir, git.Repo) for further processing.
    """
    repo = git.Repo(path, search_parent_directories=True)

    # if subdirs, just scan each one and return the results
    if subdirs:
        dir = Dir(path=path, files=[], dirs=[])
        for subdir in subdirs:
            dir.dirs.append(
                _scan(
                    path / subdir, processors, ignore_patterns or [], repo, 0, max_depth
                )
            )
        return dir, repo

    # otherwise read everything up to max_depth
    return _scan(path, processors, ignore_patterns or [], repo, 0, max_depth), repo
